config/routes.rb
Minitodo::Application.routes.draw do
  get "home/index"
  get "home/docs"
  get "home/about"
  get "home/contact_us"

  resources :projects
  resources :todos

  match 'signup' => 'users#new', :as => :signup
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'login' => 'sessions#new', :as => :login

  resources :sessions
  resources :users

  root :to => "home#index"

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :title, :notes, :user_id, :tags, :color, :icon_url, :active
  
  validates_uniqueness_of :title,  :scope => :user_id # only one 'PERSONAL' for user 'XXX'
  
  belongs_to :user
  
  def name
    title
  end
  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  
  before_filter :login_required #, :except => [:index, :show]
  
  def index
    @projects = Project.all
  end
  
  def show
    @project = Project.find(params[:id])
  end
  
  def new
    @project = Project.new
  end
  
  def create
    @project = Project.new(params[:project])
    if @project.save
      flash[:notice] = "Successfully created project."
      redirect_to @project
    else
      render :action => 'new'
    end
  end
  
  def edit
    @project = Project.find(params[:id])
  end
  
  def update
    @project = Project.find(params[:id])
    if @project.update_attributes(params[:project])
      flash[:notice] = "Successfully updated project."
      redirect_to @project
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    flash[:notice] = "Successfully destroyed project."
    redirect_to projects_url
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  
  def title_column(project)
    "<font color='#{project.color}'>#{link_to( project.title, project, :border => 0, :class=> :project)}" rescue "TitleError(#{$!})"
  end
  
end

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :notes %><br />
    <%= f.text_area :notes %>
  </p>
  <p>
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </p>
  <p>
    <%= f.label :tags %><br />
    <%= f.text_field :tags %>
  </p>
  <p>
    <%= f.label :color %><br />
    <%= f.text_field :color %>
  </p>
  <p>
    <%= f.label :icon_url %><br />
    <%= f.text_field :icon_url %>
  </p>
  <p>
    <%= f.label :active %><br />
    <%= f.check_box :active %>
  </p>
  <p>
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/projects/edit.html.erb
<% title "Edit Project" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @project %> |
  <%= link_to "View All", projects_path %>
</p>

app/views/projects/index.html.erb
<% title "Projects" %>

<table>
  <tr>
    <th>Title</th>
    <th>User</th>
    <th>Tags</th>
    <th>Icon Url</th>
    <th>Active</th>
    <th>User</th>
  </tr>
  <% for project in @projects %>
    <tr>
      <td><font color='<%= project.color %>'><%= project.title %></td>
      <td class='user'><%= project.user.username %></td>
      <td><%= project.tags %></td>
      <td><%= project.icon_url %></td>
      <td><%= project.active %></td>
      <td><%= link_to "Show", project %></td>
      <td><%= link_to "Edit", edit_project_path(project) %></td>
      <td><%= link_to "Destroy", project, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Project", new_project_path %></p>

app/views/projects/new.html.erb
<% title "New Project" %>

<%= render 'form' %>

<p><%= link_to "Back to List", projects_path %></p>

app/views/projects/show.html.erb
<% title "Project" %>

<p>
  <strong>Title:</strong>
  <%= @project.title %>
</p>
<p>
  <strong>Notes:</strong>
  <%= @project.notes %>
</p>
<p>
  <strong>User:</strong>
  <%= @project.user_id %>
</p>
<p>
  <strong>Tags:</strong>
  <%= @project.tags %>
</p>
<p>
  <strong>Color:</strong>
  <%= @project.color %>
</p>
<p>
  <strong>Icon Url:</strong>
  <%= @project.icon_url %>
</p>
<p>
  <strong>Active:</strong>
  <%= @project.active %>
</p>
<p>
  <strong>User:</strong>
  <%= @project.user_id %>
</p>

<p>
  <%= link_to "Edit", edit_project_path(@project) %> |
  <%= link_to "Destroy", @project, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", projects_path %>
</p>