config/routes.rb
Minitodo::Application.routes.draw do
  get "home/index"
  get "home/docs"
  get "home/about"
  get "home/contact_us"

  resources :projects
  resources :todos

  match 'signup' => 'users#new', :as => :signup
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'login' => 'sessions#new', :as => :login

  resources :sessions
  resources :users

  root :to => "home#index"

end

app/models/todo.rb
class Todo < ActiveRecord::Base
  attr_accessible :title, :notes, :user_id, :tags, :priority, :due, :project_id, :completed
  
  validates_uniqueness_of :title # per ora, :email, :allow_blank => true
  validates_exclusion_of :attribute, :in => %w( mov avi ), :on => :create, :message => "extension %s is not allowed"
  validates_associated :user #, :on => :create
  validates_associated :project #, :on => :create
  validates_inclusion_of :priority, :in => 1..5 , :message => "number must be in 1..5!"
  belongs_to :user
  belongs_to :project  
  
  #Todo.with_scope(:find => {:conditions => "user_id = #{current_user.id}"},
  #                :create => {:user_id => current_user.id}) do
  # user_posts = Post.find(:all)
  
  
  
  def before_save
    notes ||= '_NO_NOTES_'
    notes += "Added by Todo::before_save"
    user_id ||= current_user.id rescue 1
  end
  
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  
  before_filter :login_required #, :except => [:index, :show]
  
  def index
    @todos = Todo.all
    #@todos = Todo.find_all_by_user_id 1 # current_user.id
  end
  
  def show
    @todo = Todo.find(params[:id])
  end
  
  def new
    @todo = Todo.new
  end
  
  def create
    #params[:user_id] ||= 1 # current_user
    @todo = Todo.new(params[:todo])
    if @todo.save
      flash[:notice] = "Successfully created todo."
      redirect_to @todo
    else
      render :action => 'new'
    end
  end
  
  def edit
    @todo = Todo.find(params[:id])
  end
  
  def update
    @todo = Todo.find(params[:id])
    if @todo.update_attributes(params[:todo])
      flash[:notice] = "Successfully updated todo."
      redirect_to @todo
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy
    flash[:notice] = "Successfully destroyed todo."
    redirect_to todos_url
  end
end

app/helpers/todos_helper.rb
module TodosHelper
  
  def priority_column(todo)
    "#{todo.priority}!!"
  end
  
end

app/views/todos/_active_ones.html.erb
<% title "Active Todos" %>

<h2 >Active todos for ???</h2>

These are your active todos.

<table>
  <tr>
    <th>Title</th>
    <th>User</th>
    <th>Tags</th>
    <th>Priority</th>
    <th>Due</th>
    <th>Project</th>
    <th>Completed</th>
  </tr>
  <% for todo in @todos %>
    <tr>
      <td><b><%= link_to todo.title, todo %></b></td>
      <td><%= user_column(todo.user) %></td>
      <td><%= todo.tags %></td>
      <td><%= priority_column todo %></td>
      <td><%= todo.due %></td>
      <td><%= title_column(todo.project) %></td>
      <td><%= todo.completed %></td>
      <td><%= link_to "Show", todo %></td>
      <td><%= link_to "Edit", edit_todo_path(todo) %></td>
      <td><%= link_to "Destroy", todo, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Todo", new_todo_path %></p>

app/views/todos/_form.html.erb
<%= form_for @todo do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :notes %><br />
    <%= f.text_area :notes %>
  </p>
  <p>
    <%= f.label :tags %><br />
    <%= f.text_field :tags %>
  </p>
  <p>
    <%= f.label :priority %><br />
    <%= f.text_field :priority %>
  </p>
  <p>
    <%= f.label :due %><br />
    <%= f.date_select :due %>
  </p>
  <p>
    <%= f.label :project_id %><br />
    <%= f.text_field :project_id %>
  </p>
  <p>
    <%= f.label :completed %><br />
    <%= f.check_box :completed %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/todos/edit.html.erb
<% title "Edit Todo" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @todo %> |
  <%= link_to "View All", todos_path %>
</p>

app/views/todos/index.html.erb
<% title "Todos" %>

<table>
  <tr>
    <th>Title</th>
    <th>User</th>
    <th>Tags</th>
    <th>Priority</th>
    <th>Due</th>
    <th>Project</th>
    <th>Completed</th>
  </tr>
  <% for todo in @todos %>
    <tr>
      <td><b><%= link_to todo.title, todo %></b></td>
      <td><%= todo.user.username %></td>
      <td><%= todo.tags %></td>
      <td><%= priority_column todo %></td>
      <td><%= todo.due %></td>
      <td><%= title_column(todo.project) %></td>
      <td><%= todo.completed %></td>
      <td><%= link_to "Show", todo %></td>
      <td><%= link_to "Edit", edit_todo_path(todo) %></td>
      <td><%= link_to "Destroy", todo, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Todo", new_todo_path %></p>

app/views/todos/new.html.erb
<% title "New Todo" %>

<%= render 'form' %>

<p><%= link_to "Back to List", todos_path %></p>

app/views/todos/show.html.erb
<% title @todo.title  %>

<p>
  <strong>Notes:</strong>
  <%= @todo.notes %>
</p>
<p>
  <strong>User:</strong>
  <%= @todo.user_id %>
</p>
<p>
  <strong>Tags:</strong>
  <%= @todo.tags %>
</p>
<p>
  <strong>Priority:</strong>
  <%= @todo.priority %>
</p>
<p>
  <strong>Due:</strong>
  <%= @todo.due %>
</p>
<p>
  <strong>Group:</strong>
  <%= @todo.project_id %>
</p>
<p>
  <strong>Completed:</strong>
  <%= @todo.completed %>
</p>

<p>
  <%= link_to "Edit", edit_todo_path(@todo) %> |
  <%= link_to "Destroy", @todo, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", todos_path %>
</p>