config/routes.rb
Minitodo::Application.routes.draw do
  get "home/index"
  get "home/docs"
  get "home/about"
  get "home/contact_us"

  resources :projects
  resources :todos

  match 'signup' => 'users#new', :as => :signup
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'login' => 'sessions#new', :as => :login

  resources :sessions
  resources :users

  root :to => "home#index"

end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { page_title.to_s }
    @show_title = show_title
  end
  
  def show_title?
    @show_title
  end
  
  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end
  
  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/_login_stuff.html.erb
<% if logged_in? %>
  Welcome <%= raw user_column(current_user) %>! Not you?
  <%= link_to "Log out", logout_path %>
<% else %>
  <%= link_to "Sign up", signup_path %> or
  <%= link_to "log in", login_path %>.
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) || "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
	<div id='header'>
		<div align='right' class='login_stuff' >
			<%= render :partial => "layouts/login_stuff" %>
		</div>
		<div align='center' class='model_menu' >
		[
		 <%= link_to 'Home','/' %> |
		 <%= link_to 'Todos','/todos' %> |
		 <%= link_to 'Projects',"/projects" %> 
		]
		</div>
	</div>
	
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>

	<hr/>
	<div id='footer'>
	[
	 <%= link_to 'Home','/' %> |
	 <%= link_to 'Contact Us','/home/contact_us' %> |
	 <%= link_to 'Docs','/home/docs' %> |
	 <%= link_to 'About','/home/about' %>
	]
	</div>
  </body>
</html>